packages:
  - 'packages/*'
  - 'apps/*'
enablePrePostScripts: true
onlyBuiltDependencies:
  - esbuild
  - "@duckdb/node-bindings-darwin-arm64"
  - "@duckdb/node-bindings-darwin-x64"
  - "@duckdb/node-bindings-linux-x64"
  - "@duckdb/node-bindings-linux-arm64"
  - "@duckdb/node-bindings-win32-x64"
  - electron
